#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while (1==1) {
	motor[port1] = vexRT[Ch2] + vexRT[Ch3];
	motor[port2] = vexRT[Ch2] + vexRT[Ch3];
	motor[port9] = vexRT[Ch2] + vexRT[Ch3];
	motor[port10] = vexRT[Ch2] + vexRT[Ch3];

	//motor[port1] = vexRT[Ch3];
	//motor[port2] = vexRT[Ch2];
	//motor[port9] = vexRT[Ch2];
	//motor[port10] = vexRT[Ch2];
}


}
